Hm 03
Igor-Pino/nodejs-homework-rest-api pull request #4
Opened 2022-01-29 12:07 UTC by Igor-Pino

2022-01-30 09:22 UTC, KirillKulakow commented on .env
> +DB_HOST=mongodb+srv://IgorPino:Sobaka1108@cluster0.jvahv.mongodb.net/contact_book?retryWrites=true&w=majority
файл удалить и добавить в гитигнор

2022-01-30 09:23 UTC, KirillKulakow commented on controllers/contacts/addContact.js
> +        if(error.message.includes('validation failed')){
зачем это?

2022-01-30 09:24 UTC, KirillKulakow commented on controllers/contacts/getContactById.js
> +    if(error.message.includes('Cast to ObjectId failed')){
для проверки на валидность ид лучше использовать mongoose.Types.ObjectId.isValid
сделать проверку перед поиском
этот вариант удалить

2022-01-30 09:25 UTC, KirillKulakow commented on controllers/contacts/patchContactById.js
> +       const {id} = req.params;
сделать проверку как я писал в прошлых комментах

2022-01-30 09:25 UTC, KirillKulakow commented on controllers/contacts/removeContactById.js
>          const {id} = req.params;
проверка ид

2022-01-30 09:25 UTC, KirillKulakow commented on controllers/contacts/updateContactById.js
> +       const {id} = req.params;
проверка ид

2022-01-30 09:25 UTC, KirillKulakow commented on env.example
> +DB_HOST=
что с этим файлом?

2022-01-30 09:27 UTC, KirillKulakow requested changes
Need fix

2022-01-30 11:12 UTC, Igor-Pino commented on controllers/contacts/addContact.js
> +        if(error.message.includes('validation failed')){
Богдан на лекціях говорив, якщо контакт не пройде превірку mongoose то викидується помилка 500, а потрібна 400. Тому показав такий метод.

2022-01-31 20:31 UTC, KirillKulakow commented on .env
> +DB_HOST=mongodb+srv://IgorPino:Sobaka1108@cluster0.jvahv.mongodb.net/contact_book?retryWrites=true&w=majority
файл не удален

2022-01-31 20:34 UTC, KirillKulakow commented on env.example
> +    "phone": "(233) 738-2360",
что это за параметры?

2022-01-31 20:34 UTC, KirillKulakow requested changes
need fix

2022-01-31 21:14 UTC, Igor-Pino commented on env.example
> +    "phone": "(233) 738-2360",
я видалив цей файл потім зробив коміт, не бачу його.

2022-01-31 21:38 UTC, KirillKulakow approved these changes

2022-02-01 09:35 UTC, merged