Hw 5 avatar
Igor-Pino/nodejs-homework-rest-api pull request #6
Opened 2022-02-12 10:57 UTC by Igor-Pino

2022-02-12 20:34 UTC, KirillKulakow commented on controllers/auth/patchAvatar.js
> +        console.log("result upload: ", req.file)
удалить

2022-02-12 20:35 UTC, KirillKulakow commented on controllers/auth/patchAvatar.js
> +        const avatarURL = path.join('avatars', newFileName);
желательно создавать ссылку на аватар так, чтобы при получении данной ссылки ты мог просто перейти по ней и получить аватарку, например http://localhost:3000/public/avatars/image.jpg

2022-02-12 20:36 UTC, KirillKulakow commented on controllers/auth/register.js
> +        const avatarURL = gravatar.url(email);
добавь в данный метод опцию протокола для вывода полноценной ссылки на аватар

2022-02-12 20:37 UTC, KirillKulakow commented on middlewares/upload.js
> +    filename:(req, file, cb) => {
если будет желание можешь добавить проверку на корректный формат файла
чтобы можно было загрузить только картинку

2022-02-12 20:37 UTC, KirillKulakow requested changes
Need fix

2022-02-13 15:12 UTC, KirillKulakow commented on controllers/auth/register.js
> +        const avatarURL = gravatar.url(email);
добавь опцию протокола! https://www.npmjs.com/package/gravatar

2022-02-13 15:12 UTC, KirillKulakow requested changes
Need fix

2022-02-13 15:52 UTC, Igor-Pino commented on controllers/auth/register.js
> +        const avatarURL = gravatar.url(email);
я не зрозумів що це одразу.

2022-02-13 16:15 UTC, KirillKulakow approved these changes

2022-02-13 16:16 UTC, KirillKulakow commented on controllers/auth/register.js
> +        const avatarURL = gravatar.url(email);
если чего то не понимаешь напиши

2022-02-14 11:56 UTC, merged